version: "3.3"

services:
  apisix:
    container_name: apisix
    image: apache/apisix:2.15.0-alpine
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "80:9080/tcp"
      - "443:9443/tcp"
    networks:
      apisix:

  etcd:
    container_name: etcd
    image: bitnami/etcd:3.4.23
    restart: always
    volumes:
      - ./etcd_data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

  apisix-dashboard:
    container_name: apisix-dashboard
    image: apache/apisix-dashboard:2.15.0-alpine
    ports:
      - 9000:9000
    volumes:
      - ./apisix-dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    networks:
      apisix:

networks:
  apisix:
    driver: bridge
